// ============================================
// DAX MEASURES FOR FUND, MARKET & REGION FILTERING
// ============================================

// ============================================
// SECTION 1: PROPERTY COUNT MEASURES
// ============================================

// Total Properties (Base Measure)
Total Properties Count = 
COUNTROWS(dim_property)

// Active Properties Only
Active Properties Count = 
CALCULATE(
    COUNTROWS(dim_property),
    dim_fp_buildingcustomdata[status] = "Acquired",
    ISBLANK(dim_fp_buildingcustomdata[disposition date])
)

// Properties by Fund
Properties by Fund = 
CALCULATE(
    COUNTROWS(dim_property),
    USERELATIONSHIP(dim_property[property id], dim_fp_buildingcustomdata[hmy property]),
    NOT(ISBLANK(dim_fp_buildingcustomdata[fund]))
)

// Properties by Market
Properties by Market = 
CALCULATE(
    COUNTROWS(dim_property),
    USERELATIONSHIP(dim_property[property id], dim_fp_buildingcustomdata[hmy property]),
    NOT(ISBLANK(dim_fp_buildingcustomdata[market]))
)

// Properties by Region
Properties by Region = 
VAR CurrentRegion = SELECTEDVALUE(dim_market_region[region])
RETURN
CALCULATE(
    COUNTROWS(dim_property),
    FILTER(
        dim_fp_buildingcustomdata,
        dim_fp_buildingcustomdata[market] IN 
        CALCULATETABLE(
            VALUES(dim_market_region[market]),
            dim_market_region[region] = CurrentRegion
        )
    )
)

// ============================================
// SECTION 2: AREA MEASURES BY FUND/MARKET
// ============================================

// Total Rentable Area by Fund
Rentable Area by Fund = 
CALCULATE(
    SUM(dim_property[rentable area]),
    USERELATIONSHIP(dim_property[property id], dim_fp_buildingcustomdata[hmy property]),
    NOT(ISBLANK(dim_fp_buildingcustomdata[fund]))
)

// Total Rentable Area by Market
Rentable Area by Market = 
CALCULATE(
    SUM(dim_property[rentable area]),
    USERELATIONSHIP(dim_property[property id], dim_fp_buildingcustomdata[hmy property]),
    NOT(ISBLANK(dim_fp_buildingcustomdata[market]))
)

// Fund Portfolio Mix (%)
Fund Portfolio Mix % = 
VAR TotalArea = 
    CALCULATE(
        SUM(dim_property[rentable area]),
        ALL(dim_fp_buildingcustomdata[fund])
    )
VAR FundArea = SUM(dim_property[rentable area])
RETURN
DIVIDE(FundArea, TotalArea, 0)

// Market Concentration (%)
Market Concentration % = 
VAR TotalArea = 
    CALCULATE(
        SUM(dim_property[rentable area]),
        ALL(dim_fp_buildingcustomdata[market])
    )
VAR MarketArea = SUM(dim_property[rentable area])
RETURN
DIVIDE(MarketArea, TotalArea, 0)

// ============================================
// SECTION 3: FINANCIAL MEASURES BY FUND/MARKET
// ============================================

// NOI by Fund
NOI by Fund = 
CALCULATE(
    [NOI (Net Operating Income)],
    USERELATIONSHIP(dim_property[property id], dim_fp_buildingcustomdata[hmy property]),
    NOT(ISBLANK(dim_fp_buildingcustomdata[fund]))
)

// NOI by Market
NOI by Market = 
CALCULATE(
    [NOI (Net Operating Income)],
    USERELATIONSHIP(dim_property[property id], dim_fp_buildingcustomdata[hmy property]),
    NOT(ISBLANK(dim_fp_buildingcustomdata[market]))
)

// NOI by Region
NOI by Region = 
VAR CurrentRegion = SELECTEDVALUE(dim_market_region[region])
VAR MarketsInRegion = 
    CALCULATETABLE(
        VALUES(dim_market_region[market]),
        dim_market_region[region] = CurrentRegion
    )
RETURN
CALCULATE(
    [NOI (Net Operating Income)],
    FILTER(
        dim_fp_buildingcustomdata,
        dim_fp_buildingcustomdata[market] IN MarketsInRegion
    )
)

// ============================================
// SECTION 4: OCCUPANCY MEASURES BY FUND/MARKET
// ============================================

// Physical Occupancy by Fund
Physical Occupancy by Fund % = 
CALCULATE(
    [Physical Occupancy %],
    USERELATIONSHIP(dim_property[property id], dim_fp_buildingcustomdata[hmy property]),
    NOT(ISBLANK(dim_fp_buildingcustomdata[fund]))
)

// Physical Occupancy by Market
Physical Occupancy by Market % = 
CALCULATE(
    [Physical Occupancy %],
    USERELATIONSHIP(dim_property[property id], dim_fp_buildingcustomdata[hmy property]),
    NOT(ISBLANK(dim_fp_buildingcustomdata[market]))
)

// ============================================
// SECTION 5: HIERARCHY NAVIGATION MEASURES
// ============================================

// Selected Fund
Selected Fund = 
IF(
    HASONEVALUE(dim_fund[fund]),
    VALUES(dim_fund[fund]),
    "All Funds"
)

// Selected Market
Selected Market = 
IF(
    HASONEVALUE(dim_market_region[market]),
    VALUES(dim_market_region[market]),
    "All Markets"
)

// Selected Region
Selected Region = 
IF(
    HASONEVALUE(dim_market_region[region]),
    VALUES(dim_market_region[region]),
    "All Regions"
)

// Drill Path (for hierarchy navigation)
Drill Path = 
VAR RegionSelected = NOT(ISBLANK(SELECTEDVALUE(dim_market_region[region])))
VAR MarketSelected = NOT(ISBLANK(SELECTEDVALUE(dim_market_region[market])))
VAR PropertySelected = NOT(ISBLANK(SELECTEDVALUE(dim_property[property name])))
RETURN
IF(PropertySelected, "Property",
    IF(MarketSelected, "Market",
        IF(RegionSelected, "Region", "Portfolio")))

// ============================================
// SECTION 6: CROSS-FILTER VALIDATION MEASURES
// ============================================

// Properties After Fund Filter
Properties After Fund Filter = 
VAR SelectedFunds = VALUES(dim_fund[fund])
RETURN
CALCULATE(
    COUNTROWS(dim_property),
    dim_fp_buildingcustomdata[fund] IN SelectedFunds
)

// Properties After Market Filter
Properties After Market Filter = 
VAR SelectedMarkets = VALUES(dim_market_region[market])
RETURN
CALCULATE(
    COUNTROWS(dim_property),
    dim_fp_buildingcustomdata[market] IN SelectedMarkets
)

// Properties After Combined Filters
Properties After Combined Filters = 
VAR SelectedFunds = VALUES(dim_fund[fund])
VAR SelectedMarkets = VALUES(dim_market_region[market])
RETURN
CALCULATE(
    COUNTROWS(dim_property),
    dim_fp_buildingcustomdata[fund] IN SelectedFunds,
    dim_fp_buildingcustomdata[market] IN SelectedMarkets
)

// Filter Status (for debugging)
Filter Status = 
VAR FundFilter = IF(ISFILTERED(dim_fund[fund]), "Fund: " & CONCATENATEX(VALUES(dim_fund[fund]), dim_fund[fund], ", "), "Fund: All")
VAR MarketFilter = IF(ISFILTERED(dim_market_region[market]), "Market: " & CONCATENATEX(VALUES(dim_market_region[market]), dim_market_region[market], ", "), "Market: All")
VAR RegionFilter = IF(ISFILTERED(dim_market_region[region]), "Region: " & CONCATENATEX(VALUES(dim_market_region[region]), dim_market_region[region], ", "), "Region: All")
RETURN
FundFilter & " | " & MarketFilter & " | " & RegionFilter

// ============================================
// SECTION 7: PERFORMANCE COMPARISON MEASURES
// ============================================

// Fund Performance Ranking
Fund Performance Ranking = 
RANKX(
    ALL(dim_fund[fund]),
    [NOI by Fund],
    ,
    DESC,
    Dense
)

// Market Performance Ranking
Market Performance Ranking = 
RANKX(
    ALL(dim_market_region[market]),
    [NOI by Market],
    ,
    DESC,
    Dense
)

// Fund vs Portfolio Average NOI
Fund vs Portfolio Avg NOI = 
VAR CurrentFundNOI = [NOI by Fund]
VAR PortfolioAvgNOI = 
    CALCULATE(
        AVERAGEX(
            VALUES(dim_fund[fund]),
            [NOI by Fund]
        ),
        ALL(dim_fund)
    )
RETURN
CurrentFundNOI - PortfolioAvgNOI

// Market vs Region Average Occupancy
Market vs Region Avg Occupancy = 
VAR CurrentMarketOcc = [Physical Occupancy by Market]
VAR CurrentRegion = SELECTEDVALUE(dim_market_region[region])
VAR RegionAvgOcc = 
    CALCULATE(
        AVERAGEX(
            FILTER(
                ALL(dim_market_region),
                dim_market_region[region] = CurrentRegion
            ),
            [Physical Occupancy by Market]
        )
    )
RETURN
CurrentMarketOcc - RegionAvgOcc

// ============================================
// SECTION 8: DYNAMIC TITLES FOR VISUALS
// ============================================

// Dynamic Title - Fund Analysis
Dynamic Title Fund = 
"Fund Performance: " & [Selected Fund]

// Dynamic Title - Market Analysis  
Dynamic Title Market = 
"Market Analysis: " & [Selected Market]

// Dynamic Title - Regional Overview
Dynamic Title Regional = 
[Selected Region] & " Regional Overview"

// Dynamic Subtitle with Filters
Dynamic Subtitle = 
VAR PropertyCount = [Properties After Combined Filters]
VAR TotalProperties = CALCULATE([Total Properties Count], ALL())
RETURN
"Showing " & PropertyCount & " of " & TotalProperties & " properties | " & [Filter Status]