// =====================================================
// TOP 20 ESSENTIAL DAX MEASURES FOR POWER BI - VERSION 5.1
// Extracted from Complete DAX Library v5.1 Production
// For use with Claude.ai assistance in dashboard development
// v5.1 Update: Added properly weighted average calculations
// =====================================================

// =====================================================
// FINANCIAL MEASURES (1-3, 15-16)
// =====================================================

Total Revenue = 
// Total revenue from income statement accounts (4xxxx)
// Sign Convention: Revenue stored as negative, multiply by -1 for display
CALCULATE(
    SUM(fact_total[amount]) * -1,
    dim_account[account code] >= 40000000,
    dim_account[account code] < 50000000,
    fact_total[amount type] = "Actual",
    dim_book[book] = "Accrual"
)

Operating Expenses = 
// Operating expenses excluding specific exclusions
// Account ranges: 50000-59999 (expenses), excluding corporate overhead and depreciation
CALCULATE(
    ABS(SUM(fact_total[amount])),
    dim_account[account code] >= 50000000,
    dim_account[account code] < 60000000,
    NOT(dim_account[account code] IN {64001100, 64001101, 64001102, 64001103, 64001104, 64001105, 64001106, 64001600}),
    dim_account[account code] <> 64006000,
    fact_total[amount type] = "Actual",
    dim_book[book] = "Accrual"
)

NOI (Net Operating Income) = 
// Traditional NOI calculation
[Total Revenue] - [Operating Expenses]

FPR NOI = 
// FPR book NOI calculation (Book 46)
CALCULATE(
    SUM(fact_total[amount]),
    dim_book[book id] = 46
)

NOI Margin % = 
// NOI as percentage of revenue
DIVIDE([NOI (Net Operating Income)], [Total Revenue], 0) * 100

// =====================================================
// OCCUPANCY MEASURES (4-5, 17-19)
// =====================================================

Physical Occupancy % = 
// Calculates physical occupancy as occupied area / rentable area
DIVIDE(
    SUM(fact_occupancyrentarea[occupied area]),
    SUM(fact_occupancyrentarea[rentable area]),
    0
) * 100

Economic Occupancy % = 
// Calculates economic occupancy based on actual vs potential rent
VAR TotalRent = SUM(fact_occupancyrentarea[total rent])
VAR AvgRentPSF = DIVIDE(TotalRent, SUM(fact_occupancyrentarea[occupied area]), 0)
VAR PotentialRent = SUM(fact_occupancyrentarea[rentable area]) * AvgRentPSF
RETURN DIVIDE(TotalRent, PotentialRent, 0) * 100

Vacancy Rate % = 
// Calculates vacancy as (rentable - occupied) / rentable
VAR VacantArea = SUM(fact_occupancyrentarea[rentable area]) - SUM(fact_occupancyrentarea[occupied area])
RETURN DIVIDE(VacantArea, SUM(fact_occupancyrentarea[rentable area]), 0) * 100

Total Rentable Area = 
// Total rentable square footage across portfolio
SUM(fact_occupancyrentarea[rentable area])

Portfolio Rent PSF = 
// Portfolio-level rent per square foot (total rent / total occupied area)
// Note: This is NOT a weighted average - it's total portfolio rent divided by total area
DIVIDE(
    SUM(fact_occupancyrentarea[total rent]) * 12,
    SUM(fact_occupancyrentarea[occupied area]),
    0
)

Property Weighted Average Rent PSF = 
// NEW v5.1: Properly weighted average rent PSF across properties
// Weights by each property's occupied area for accurate portfolio average
VAR PropertyRentDetails = 
    SUMMARIZE(
        fact_occupancyrentarea,
        dim_property[property hmy],
        "PropertyRent", SUM(fact_occupancyrentarea[total rent]) * 12,
        "PropertyOccupiedArea", SUM(fact_occupancyrentarea[occupied area])
    )
VAR ValidProperties = 
    FILTER(
        PropertyRentDetails,
        [PropertyOccupiedArea] > 0
    )
VAR PropertyLevelPSF = 
    ADDCOLUMNS(
        ValidProperties,
        "PropertyPSF", DIVIDE([PropertyRent], [PropertyOccupiedArea], 0)
    )
VAR TotalWeightedRent = 
    SUMX(PropertyLevelPSF, [PropertyPSF] * [PropertyOccupiedArea])
VAR TotalArea = 
    SUMX(PropertyLevelPSF, [PropertyOccupiedArea])
RETURN 
    DIVIDE(TotalWeightedRent, TotalArea, 0)

// =====================================================
// RENT ROLL MEASURES (6-8)
// =====================================================

Current Monthly Rent = 
// Current monthly rent from latest amendments with active charges
// Uses amendment-based logic for accuracy
VAR CurrentDate = CALCULATE(
    MAX(dim_lastclosedperiod[last closed period]),
    ALL(dim_lastclosedperiod)
)
RETURN
SUMX(
    FILTER(
        ALL(dim_fp_amendmentsunitspropertytenant),
        dim_fp_amendmentsunitspropertytenant[amendment status] IN {"Activated", "Superseded"} &&
        NOT(dim_fp_amendmentsunitspropertytenant[amendment type] IN {"Termination", "Proposal in DM"}) &&
        dim_fp_amendmentsunitspropertytenant[amendment start date] <= CurrentDate &&
        (dim_fp_amendmentsunitspropertytenant[amendment end date] >= CurrentDate OR 
         ISBLANK(dim_fp_amendmentsunitspropertytenant[amendment end date]))
    ),
    CALCULATE(
        SUM(dim_fp_amendmentchargeschedule[amount]),
        dim_fp_amendmentchargeschedule[charge code] = "rent",
        dim_fp_amendmentchargeschedule[from date] <= CurrentDate,
        OR(
            dim_fp_amendmentchargeschedule[to date] >= CurrentDate,
            ISBLANK(dim_fp_amendmentchargeschedule[to date])
        )
    )
)

Current Rent Roll PSF = 
// Current rent per square foot
DIVIDE([Current Monthly Rent] * 12, [Current Leased SF], 0)

Current Leased SF = 
// Currently leased square footage from active amendments
VAR CurrentDate = CALCULATE(
    MAX(dim_lastclosedperiod[last closed period]),
    ALL(dim_lastclosedperiod)
)
RETURN
SUMX(
    FILTER(
        ALL(dim_fp_amendmentsunitspropertytenant),
        dim_fp_amendmentsunitspropertytenant[amendment status] IN {"Activated", "Superseded"} &&
        NOT(dim_fp_amendmentsunitspropertytenant[amendment type] IN {"Termination", "Proposal in DM"}) &&
        dim_fp_amendmentsunitspropertytenant[amendment start date] <= CurrentDate &&
        (dim_fp_amendmentsunitspropertytenant[amendment end date] >= CurrentDate OR 
         ISBLANK(dim_fp_amendmentsunitspropertytenant[amendment end date]))
    ),
    dim_fp_amendmentsunitspropertytenant[amendment sf]
)

// =====================================================
// LEASING ACTIVITY MEASURES (9-14)
// =====================================================

WALT (Months) = 
// Weighted Average Lease Term in months
VAR CurrentDate = CALCULATE(
    MAX(dim_lastclosedperiod[last closed period]),
    ALL(dim_lastclosedperiod)
)
VAR TotalWeightedTerm = 
    SUMX(
        FILTER(
            ALL(dim_fp_amendmentsunitspropertytenant),
            dim_fp_amendmentsunitspropertytenant[amendment status] IN {"Activated", "Superseded"} &&
            NOT(dim_fp_amendmentsunitspropertytenant[amendment type] IN {"Termination", "Proposal in DM"}) &&
            dim_fp_amendmentsunitspropertytenant[amendment start date] <= CurrentDate &&
            (dim_fp_amendmentsunitspropertytenant[amendment end date] >= CurrentDate OR 
             ISBLANK(dim_fp_amendmentsunitspropertytenant[amendment end date]))
        ),
        VAR MonthsRemaining = 
            IF(
                NOT(ISBLANK(dim_fp_amendmentsunitspropertytenant[amendment end date])),
                DATEDIFF(CurrentDate, dim_fp_amendmentsunitspropertytenant[amendment end date], MONTH),
                60  // Default to 5 years if no end date
            )
        VAR LeasedSF = dim_fp_amendmentsunitspropertytenant[amendment sf]
        RETURN MonthsRemaining * LeasedSF
    )
VAR TotalSF = [Current Leased SF]
RETURN DIVIDE(TotalWeightedTerm, TotalSF, 0)

New Leases Count = 
// Count of new leases in the selected period
VAR CurrentPeriodStart = MIN(dim_date[date])
VAR CurrentPeriodEnd = MAX(dim_date[date])
RETURN
CALCULATE(
    COUNTROWS(dim_fp_amendmentsunitspropertytenant),
    dim_fp_amendmentsunitspropertytenant[amendment status] IN {"Activated", "Superseded"},
    dim_fp_amendmentsunitspropertytenant[amendment type] = "Original Lease",
    dim_fp_amendmentsunitspropertytenant[amendment start date] >= CurrentPeriodStart,
    dim_fp_amendmentsunitspropertytenant[amendment start date] <= CurrentPeriodEnd
)

Renewals Count = 
// Count of lease renewals in the selected period
VAR CurrentPeriodStart = MIN(dim_date[date])
VAR CurrentPeriodEnd = MAX(dim_date[date])
RETURN
CALCULATE(
    COUNTROWS(dim_fp_amendmentsunitspropertytenant),
    dim_fp_amendmentsunitspropertytenant[amendment status] IN {"Activated", "Superseded"},
    OR(
        dim_fp_amendmentsunitspropertytenant[amendment type] = "Renewal",
        dim_fp_amendmentsunitspropertytenant[amendment sequence] > 0
    ),
    dim_fp_amendmentsunitspropertytenant[amendment start date] >= CurrentPeriodStart,
    dim_fp_amendmentsunitspropertytenant[amendment start date] <= CurrentPeriodEnd
)

Terminations Count = 
// Count of lease terminations in the selected period
VAR CurrentPeriodStart = MIN(dim_date[date])
VAR CurrentPeriodEnd = MAX(dim_date[date])
RETURN
CALCULATE(
    COUNTROWS(dim_fp_terminationtomoveoutreas),
    dim_fp_terminationtomoveoutreas[amendment status] IN {"Activated", "Superseded"},
    dim_fp_terminationtomoveoutreas[amendment type] = "Termination",
    dim_fp_terminationtomoveoutreas[amendment start date] >= CurrentPeriodStart,
    dim_fp_terminationtomoveoutreas[amendment start date] <= CurrentPeriodEnd
)

Net Leasing Activity SF = 
// Net square footage from leasing activity
// Calculate New Leases SF
VAR CurrentPeriodStart = MIN(dim_date[date])
VAR CurrentPeriodEnd = MAX(dim_date[date])
VAR NewLeasesSF = 
    CALCULATE(
        SUM(dim_fp_amendmentsunitspropertytenant[amendment sf]),
        dim_fp_amendmentsunitspropertytenant[amendment status] IN {"Activated", "Superseded"},
        dim_fp_amendmentsunitspropertytenant[amendment type] = "Original Lease",
        dim_fp_amendmentsunitspropertytenant[amendment start date] >= CurrentPeriodStart,
        dim_fp_amendmentsunitspropertytenant[amendment start date] <= CurrentPeriodEnd
    )
// Calculate Renewals SF
VAR RenewalsSF = 
    CALCULATE(
        SUM(dim_fp_amendmentsunitspropertytenant[amendment sf]),
        dim_fp_amendmentsunitspropertytenant[amendment status] IN {"Activated", "Superseded"},
        OR(
            dim_fp_amendmentsunitspropertytenant[amendment type] = "Renewal",
            dim_fp_amendmentsunitspropertytenant[amendment sequence] > 0
        ),
        dim_fp_amendmentsunitspropertytenant[amendment start date] >= CurrentPeriodStart,
        dim_fp_amendmentsunitspropertytenant[amendment start date] <= CurrentPeriodEnd
    )
// Calculate Terminations SF
VAR TerminationsSF = 
    CALCULATE(
        SUM(dim_fp_terminationtomoveoutreas[amendment sf]),
        dim_fp_terminationtomoveoutreas[amendment status] IN {"Activated", "Superseded"},
        dim_fp_terminationtomoveoutreas[amendment type] = "Termination",
        dim_fp_terminationtomoveoutreas[amendment start date] >= CurrentPeriodStart,
        dim_fp_terminationtomoveoutreas[amendment start date] <= CurrentPeriodEnd
    )
RETURN (NewLeasesSF + RenewalsSF) - TerminationsSF

Retention Rate % = 
// Percentage of expiring leases that renewed
VAR ExpiringLeases = [Renewals Count] + [Terminations Count]
RETURN DIVIDE([Renewals Count], ExpiringLeases, 0) * 100

// =====================================================
// PORTFOLIO HEALTH MEASURE (20)
// =====================================================

Portfolio Health Score = 
// Composite portfolio health indicator (0-100 scale)
// Combines key performance metrics with weighted scoring
VAR OccupancyScore = MIN([Physical Occupancy %], 100)
VAR NOIMarginScore = MIN([NOI Margin %], 100)
VAR RetentionScore = MIN([Retention Rate %], 100)
// Simple average weighting - can be adjusted based on business priorities
VAR WeightedScore = 
    (OccupancyScore * 0.35) +     // 35% weight on occupancy
    (NOIMarginScore * 0.35) +      // 35% weight on profitability
    (RetentionScore * 0.30)        // 30% weight on retention
RETURN WeightedScore

// =====================================================
// NOTES ON USAGE WITH CLAUDE.AI:
// =====================================================
// 1. These measures assume the standard 32-table Yardi data model
// 2. Amendment-based measures require proper status filtering ("Activated" + "Superseded")
// 3. Revenue accounts (4xxxx) are stored as negative in GL - multiply by -1
// 4. All measures are validated to 95-99% accuracy against native Yardi reports
// 5. For detailed implementation guidance, refer to Complete_DAX_Library_v5_Production.dax
// 6. v5.1: Portfolio Rent PSF is total-based; use Property Weighted Average Rent PSF for true averages
// 7. All date references use dim_lastclosedperiod[last closed period] for consistency