# Yardi PowerBI Dashboard Configuration
# Application settings and customization options

# Dashboard Settings
dashboard:
  title: "Yardi PowerBI Dashboard"
  subtitle: "Commercial Real Estate Analytics Platform"
  version: "5.1"
  theme: "light"
  
# Database Settings
database:
  path: "database/yardi.duckdb"
  read_only: true
  connection_timeout: 30
  query_timeout: 60
  
# Performance Settings
performance:
  cache_ttl: 300  # 5 minutes
  slow_query_threshold: 2.0  # seconds
  max_query_results: 10000
  
# UI Settings
ui:
  page_layout: "wide"
  sidebar_state: "expanded"
  chart_height: 400
  max_properties_display: 10
  
# Color Schemes
colors:
  primary: "#1f77b4"
  secondary: "#17a2b8"
  success: "#28a745"
  warning: "#ffc107"
  danger: "#dc3545"
  info: "#17a2b8"
  
# Chart Settings
charts:
  default_height: 400
  color_scales:
    revenue: "Blues"
    noi: "Greens"
    margin: "RdYlGn"
    risk: "RdYlBu"
  
# Export Settings
export:
  default_format: "csv"
  include_timestamp: true
  max_rows: 50000
  
# Error Handling
error_handling:
  show_detailed_errors: false
  log_errors: true
  max_error_display_length: 200
  
# Dashboard Components
components:
  executive_summary:
    enabled: true
    refresh_interval: 300
  rent_roll:
    enabled: true
    refresh_interval: 300
  leasing_activity:
    enabled: true
    refresh_interval: 300
  financial_metrics:
    enabled: true
    refresh_interval: 300
  credit_risk:
    enabled: true
    refresh_interval: 300
    
# Data Validation
validation:
  require_properties: true
  require_date_range: true
  min_date_range_days: 1
  max_date_range_days: 3650  # 10 years
  
# Business Logic
business:
  noi_margin_target: 50.0
  occupancy_target: 85.0
  cap_rate_target: 6.5
  credit_score_threshold: 6.0
  
# Navigation
navigation:
  default_dashboard: "Executive Summary"
  available_dashboards:
    - "Executive Summary"
    - "Rent Roll Analysis"
    - "Leasing Activity"
    - "Financial Performance"
    - "Credit Risk Analysis"
    
# Filters
filters:
  default_fund: "All Funds"
  default_book: "All Books"
  available_funds:
    - "All Funds"
    - "Fund 1"
    - "Fund 2"
    - "Fund 3"
  available_books:
    - "All Books"
    - "Book 46 (FPR)"
    - "Book 1 (Standard)"
    
# Help and Documentation
help:
  show_tooltips: true
  show_help_buttons: true
  documentation_url: "https://github.com/your-username/yardi-powerbi"
  support_email: "support@example.com"
  
# Logging
logging:
  level: "INFO"
  file: "logs/dashboard.log"
  max_file_size: "10MB"
  backup_count: 5
  
# Security
security:
  enable_authentication: false
  session_timeout: 3600  # 1 hour
  max_login_attempts: 3
  
# Monitoring
monitoring:
  enable_metrics: true
  track_user_actions: true
  performance_monitoring: true